name: Let's go

on: [push]

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Let's go
        run: echo "Hello, GitHub Actions!"
